require "lib/engine.rb"

Engine.autoload do
  require "app/controllers/levels_controller.rb"
  require "app/controllers/main_menu_controller.rb"
  require "app/effects/ossilator.rb"
  require "app/labels/header.rb"
  require "app/layers/background_layer.rb"
  require "app/levels/level.rb"
  require "app/levels/level01.rb"
  require "app/levels/level02.rb"
  require "app/levels/level03.rb"
  require "app/levels/level04.rb"
  require "app/models/ball.rb"
  require "app/models/brick.rb"
  require "app/models/menu.rb"
  require "app/models/menu/option.rb"
  require "app/models/menu/setting.rb"
  require "app/models/paddle.rb"
  require "app/screens/death_screen.rb"
  require "app/screens/in_game_menu_screen.rb"
  require "app/screens/level_screen.rb"
  require "app/screens/main_menu_screen.rb"
  require "app/screens/settings_screen.rb"
  require "app/screens/win_screen.rb"
end

require "config/colors.rb"
require "config/settings.rb"
require "config/scenes.rb"
